services:
  - type: web
    name: honeypot-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: honeypot-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false


databases:
  - name: honeypot-db
    databaseName: honeypot
    user: honeypot
